export const siteName = "Lemonyte";
export const blogName = `${siteName}'s Blog`;
export const tagline = "Open-source developer and cybersecurity student";
export const description = "Open-source developer and cybersecurity student. Explore my projects, blog, and more.";
export const baseUrl = new URL("https://lemonyte.com/");
export const websiteId = new URL("#website", baseUrl).href;
export const personId = new URL("#person", baseUrl).href;
export const githubUsername = "lemonyte";
export const pinnedRepoCount = 6;
